/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package soli.plan.pkg1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Barren extends javax.swing.JFrame {

    /**
     * Creates new form Barren
     */
    public static ArrayList<In_OutComing_goods> inComing_goods = new ArrayList<>();
    public static ArrayList<In_OutComing_goods> outComing_goods = new ArrayList<>();
    public static ArrayList<Data_current_goods> current_goods = new ArrayList<>();
    ArrayList<Data_Items_Card> list2 = new ArrayList<>();
    SimpleDateFormat date = new SimpleDateFormat("YYYY/MM/dd");
    Date dat = new Date();
    String[] items;
    static Connection connection;
    static Statement statement;
    static PreparedStatement preparedStatement;
    double In_Supply_Price = 0.0, Out_Supply_Price = 0.0, Current_Supply_Price = 0.0;
    double In_Wholesale_price = 0.0, Out_Wholesale_price = 0.0, Current_Wholesale_price = 0.0;
    double In_Consumer_selling_price = 0.0, Out_Consumer_selling_price = 0.0, Current_Consumer_selling_price = 0.0;
    
    public Barren() {
        initComponents();
        this.setResizable(false);
        this.setLocation(100, 50);
        this.setDefaultCloseOperation(Barren.DO_NOTHING_ON_CLOSE);
        jRadioButton1.setSelected(true);
        jTable1.setEnabled(false);
        jTable2.setEnabled(false);
        jTable3.setEnabled(false);
        show_data2();
        get_Incoming_goods("(جميع الاصناف)", "" + Running.date + "/01/01", date.format(dat).toString());
        get_Outcoming_goods("(جميع الاصناف)", "" + Running.date + "/01/01", date.format(dat).toString());
        get_Current_goods("(جميع الاصناف)");
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(items));
        jTextField3.setText(date.format(dat).toString().substring(0, 4));
        jTextField2.setText(date.format(dat).toString().substring(5, 7));
        jTextField1.setText(date.format(dat).toString().substring(8, 10));
        jLabel6.setText(In_Supply_Price + "");
        jLabel4.setText(Out_Supply_Price + "");
        jLabel8.setText(Current_Supply_Price + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(139, 69, 19));

        jPanel1.setBackground(new java.awt.Color(139, 69, 19));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("جرد حتي تاريخ : ");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("تاريخ اليوم");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("أسم الصنف :");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(139, 69, 19));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jRadioButton1.setBackground(new java.awt.Color(139, 69, 19));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("تقييم قيمة بضاعة الجرد حسب أسعار التوريد");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(139, 69, 19));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("تقييم قيمة بضاعة الجرد حسب أسعار الجملة");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(139, 69, 19));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("تقييم قيمة بضاعة الجرد حسب أسعار المستهلك");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soli/plan/pkg1/download15.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soli/plan/pkg1/download 4.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTabbedPane3.setBackground(new java.awt.Color(139, 69, 19));
        jTabbedPane3.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jPanel6.setBackground(new java.awt.Color(139, 69, 19));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الاجمالي", "الخصم", "السعر", "العدد", "اسم الصنف", "الحركة", "فاتورة رقم", "من خلال", "بتاريخ", "م"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(35);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setMinWidth(50);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(3).setMinWidth(50);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(4).setMinWidth(180);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(180);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(180);
            jTable1.getColumnModel().getColumn(6).setMinWidth(50);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(9).setMinWidth(50);
            jTable1.getColumnModel().getColumn(9).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(9).setMaxWidth(50);
        }

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("اجمالي قيمة البضاعة االداخلة الي المخزن");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1066, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("البضاعة الداخلة الي المخزن", jPanel6);

        jPanel7.setBackground(new java.awt.Color(139, 69, 19));

        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الاجمالي", "الخصم", "السعر", "العدد", "اسم الصنف", "الحركة", "فاتورة رقم", "الي حساب", "بتاريخ", "م"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setRowHeight(35);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(1).setMinWidth(50);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTable2.getColumnModel().getColumn(1).setMaxWidth(50);
            jTable2.getColumnModel().getColumn(3).setMinWidth(50);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTable2.getColumnModel().getColumn(3).setMaxWidth(50);
            jTable2.getColumnModel().getColumn(4).setMinWidth(180);
            jTable2.getColumnModel().getColumn(4).setPreferredWidth(180);
            jTable2.getColumnModel().getColumn(4).setMaxWidth(180);
            jTable2.getColumnModel().getColumn(6).setMinWidth(50);
            jTable2.getColumnModel().getColumn(6).setPreferredWidth(50);
            jTable2.getColumnModel().getColumn(6).setMaxWidth(50);
            jTable2.getColumnModel().getColumn(9).setMinWidth(50);
            jTable2.getColumnModel().getColumn(9).setPreferredWidth(50);
            jTable2.getColumnModel().getColumn(9).setMaxWidth(50);
        }

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("اجمالي قيمة البضاعة الخارجة من المخزن");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1066, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("البضاعة الخارجة من المخزن", jPanel7);

        jPanel8.setBackground(new java.awt.Color(139, 69, 19));

        jTable3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "اجمالي القيمة", "السعر", "الباقي", "الخارج", "الداخل", "اسم الصنف", "م"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setRowHeight(35);
        jScrollPane3.setViewportView(jTable3);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("اجمالي قيمة البضاعة الموجوده بالمخزن");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1073, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("البضاعة الموجودة بالمخزن", jPanel8);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SimpleDateFormat years = new SimpleDateFormat("YYYY");
        SimpleDateFormat month = new SimpleDateFormat("MM");
        SimpleDateFormat day = new SimpleDateFormat("dd");
        Date dat1 = new Date();
        jTextField3.setText(years.format(dat1));
        jTextField2.setText(month.format(dat1));
        jTextField1.setText(day.format(dat1));
        
        table1();
        table2();
        get_Incoming_goods(jComboBox1.getSelectedItem().toString(), "" + Running.date + "/01/01", date.format(dat).toString());
        get_Outcoming_goods(jComboBox1.getSelectedItem().toString(), "" + Running.date + "/01/01", date.format(dat).toString());
        if (jRadioButton1.isSelected()) {
            jLabel6.setText(In_Supply_Price + "");
            jLabel4.setText(Out_Supply_Price + "");
            jLabel8.setText(+Current_Supply_Price + "");
        } else if (jRadioButton2.isSelected()) {
            jLabel6.setText(In_Wholesale_price + "");
            jLabel4.setText(Out_Wholesale_price + "");
            jLabel8.setText(Current_Wholesale_price + "");
        } else if (jRadioButton3.isSelected()) {
            jLabel6.setText(In_Consumer_selling_price + "");
            jLabel4.setText(Out_Consumer_selling_price + "");
            jLabel8.setText(Current_Consumer_selling_price + "");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        table1();
        table2();
        String date = jTextField3.getText().toString();
        if (jTextField2.getText().toString().length() < 2) {
            date += "/0" + jTextField2.getText().toString();
        } else {
            date += "/" + jTextField2.getText().toString();
        }
        if (jTextField1.getText().toString().length() < 2) {
            date += "/0" + jTextField1.getText().toString();
        } else {
            date += "/" + jTextField1.getText().toString();
        }
        get_Incoming_goods(jComboBox1.getSelectedItem().toString(), "" + Running.date + "/01/01", date);
        get_Outcoming_goods(jComboBox1.getSelectedItem().toString(), "" + Running.date + "/01/01", date);
        if (jRadioButton1.isSelected()) {
            jLabel6.setText(In_Supply_Price + "");
            jLabel4.setText(Out_Supply_Price + "");
            jLabel8.setText(+Current_Supply_Price + "");
        } else if (jRadioButton2.isSelected()) {
            jLabel6.setText(In_Wholesale_price + "");
            jLabel4.setText(Out_Wholesale_price + "");
            jLabel8.setText(Current_Wholesale_price + "");
        } else if (jRadioButton3.isSelected()) {
            jLabel6.setText(In_Consumer_selling_price + "");
            jLabel4.setText(Out_Consumer_selling_price + "");
            jLabel8.setText(Current_Consumer_selling_price + "");
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        table1();
        table2();
        String date = jTextField3.getText().toString();
        if (jTextField2.getText().toString().length() < 2) {
            date += "/0" + jTextField2.getText().toString();
        } else {
            date += "/" + jTextField2.getText().toString();
        }
        if (jTextField1.getText().toString().length() < 2) {
            date += "/0" + jTextField1.getText().toString();
        } else {
            date += "/" + jTextField1.getText().toString();
        }
        get_Incoming_goods(jComboBox1.getSelectedItem().toString(), "" + Running.date + "/01/01", date);
        get_Outcoming_goods(jComboBox1.getSelectedItem().toString(), "" + Running.date + "/01/01", date);
        if (jRadioButton1.isSelected()) {
            jLabel6.setText(In_Supply_Price + "");
            jLabel4.setText(Out_Supply_Price + "");
            jLabel8.setText(+Current_Supply_Price + "");
        } else if (jRadioButton2.isSelected()) {
            jLabel6.setText(In_Wholesale_price + "");
            jLabel4.setText(Out_Wholesale_price + "");
            jLabel8.setText(Current_Wholesale_price + "");
        } else if (jRadioButton3.isSelected()) {
            jLabel6.setText(In_Consumer_selling_price + "");
            jLabel4.setText(Out_Consumer_selling_price + "");
            jLabel8.setText(Current_Consumer_selling_price + "");
        }
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        jLabel6.setText(In_Supply_Price + "");
        jLabel4.setText(Out_Supply_Price + "");
        jLabel8.setText(+Current_Supply_Price + "");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        jLabel6.setText(In_Wholesale_price + "");
        jLabel4.setText(Out_Wholesale_price + "");
        jLabel8.setText(Current_Wholesale_price + "");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        jLabel6.setText(In_Consumer_selling_price + "");
        jLabel4.setText(Out_Consumer_selling_price + "");
        jLabel8.setText(Current_Consumer_selling_price + "");
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Print_Goods().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        table1();
        table2();
        table3();
        get_Incoming_goods(jComboBox1.getSelectedItem().toString(), "" + Running.date + "/01/01", date.format(dat).toString());
        get_Outcoming_goods(jComboBox1.getSelectedItem().toString(), "" + Running.date + "/01/01", date.format(dat).toString());
        get_Current_goods(jComboBox1.getSelectedItem().toString());
        if (jRadioButton1.isSelected()) {
            jLabel6.setText(In_Supply_Price + "");
            jLabel4.setText(Out_Supply_Price + "");
            jLabel8.setText(+Current_Supply_Price + "");
        } else if (jRadioButton2.isSelected()) {
            jLabel6.setText(In_Wholesale_price + "");
            jLabel4.setText(Out_Wholesale_price + "");
            jLabel8.setText(Current_Wholesale_price + "");
        } else if (jRadioButton3.isSelected()) {
            jLabel6.setText(In_Wholesale_price + "");
            jLabel4.setText(Out_Wholesale_price + "");
            jLabel8.setText(Current_Wholesale_price + "");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barren().setVisible(true);
            }
        });
    }
    
    public void get_Incoming_goods(String search, String start_date, String end_date) {
        inComing_goods.clear();
        In_Supply_Price = 0.0;
        In_Wholesale_price = 0.0;
        In_Consumer_selling_price = 0.0;
        Security security = new Security();
        try {
            connection = security.coneect();
            if (search.equals("(جميع الاصناف)")) {
                preparedStatement = connection.prepareStatement("SELECT * FROM incoming_goods WHERE Y_id = '" + Running.Y_id + "' and date between '" + start_date + "' and '" + end_date + "' order by name_person and number_bill");
            } else {
                preparedStatement = connection.prepareStatement("SELECT * FROM incoming_goods WHERE Y_id = '" + Running.Y_id + "' and name_items = '" + search + "' and date between '" + start_date + "' and '" + end_date + "' order by name_person and number_bill");
            }
            ResultSet set = preparedStatement.executeQuery();
            DefaultTableModel mm = (DefaultTableModel) jTable1.getModel();
            Object[] col = new Object[10];
            while (set.next()) {
                In_OutComing_goods ioc = new In_OutComing_goods(set.getString("date"), set.getString("name_person"), set.getString("number_bill"), set.getString("state"), set.getString("name_items"), set.getString("number_item"), set.getString("price"), set.getString("discount"), set.getString("total"));
                inComing_goods.add(ioc);
            }
            for (int i = 0; i < inComing_goods.size(); i++) {
                col[9] = i + 1;
                col[8] = inComing_goods.get(i).date;
                col[7] = inComing_goods.get(i).name_person;
                col[6] = inComing_goods.get(i).number_bill;
                col[5] = inComing_goods.get(i).state;
                col[4] = inComing_goods.get(i).name_items;
                col[3] = inComing_goods.get(i).number_item;
                col[2] = inComing_goods.get(i).price;
                col[1] = inComing_goods.get(i).discount;
                col[0] = inComing_goods.get(i).total;
                for (int x = 0; x < list2.size(); x++) {
                    if (inComing_goods.get(i).name_items.equals(list2.get(x).getC_name())) {
                        double price = Double.parseDouble(inComing_goods.get(i).number_item) * Double.parseDouble(list2.get(x).getC_supply_price());
                        price -= ((price / 100.0) * (Double.parseDouble(inComing_goods.get(i).discount)));
                        In_Supply_Price += price;
                        
                        price = Double.parseDouble(inComing_goods.get(i).number_item) * Double.parseDouble(list2.get(x).getC_wholesale_price());
                        price -= ((price / 100.0) * (Double.parseDouble(inComing_goods.get(i).discount)));
                        In_Wholesale_price += price;
                        
                        price = Double.parseDouble(inComing_goods.get(i).number_item) * Double.parseDouble(list2.get(x).getC_Consumer_selling_price());
                        price -= ((price / 100.0) * (Double.parseDouble(inComing_goods.get(i).discount)));
                        In_Consumer_selling_price += price;
                        break;
                    }
                }
                mm.addRow(col);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                connection.close();
                preparedStatement.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }
    
    public void get_Outcoming_goods(String search, String start_date, String end_date) {
        outComing_goods.clear();
        Out_Supply_Price = 0.0;
        Out_Wholesale_price = 0.0;
        Out_Consumer_selling_price = 0.0;
        Security security = new Security();
        try {
            connection = security.coneect();
            if (search.equals("(جميع الاصناف)")) {
                preparedStatement = connection.prepareStatement("SELECT * FROM outcoming_goods WHERE Y_id = '" + Running.Y_id + "' and date between '" + start_date + "' and '" + end_date + "'order by name_person and number_bill");
            } else {
                preparedStatement = connection.prepareStatement("SELECT * FROM outcoming_goods WHERE Y_id = '" + Running.Y_id + "' and name_items = '" + search + "' and date between '" + start_date + "' and '" + end_date + "' order by name_person and number_bill");
            }
            ResultSet set = preparedStatement.executeQuery();
            DefaultTableModel mm = (DefaultTableModel) jTable2.getModel();
            Object[] col = new Object[10];
            while (set.next()) {
                In_OutComing_goods ioc = new In_OutComing_goods(set.getString("date"), set.getString("name_person"), set.getString("number_bill"), set.getString("state"), set.getString("name_items"), set.getString("number_item"), set.getString("price"), set.getString("discount"), set.getString("total"));
                outComing_goods.add(ioc);
            }
            for (int i = 0; i < outComing_goods.size(); i++) {
                col[9] = i + 1;
                col[8] = outComing_goods.get(i).date;
                col[7] = outComing_goods.get(i).name_person;
                col[6] = outComing_goods.get(i).number_bill;
                col[5] = outComing_goods.get(i).state;
                col[4] = outComing_goods.get(i).name_items;
                col[3] = outComing_goods.get(i).number_item;
                col[2] = outComing_goods.get(i).price;
                col[1] = outComing_goods.get(i).discount;
                col[0] = outComing_goods.get(i).total;
                for (int x = 0; x < list2.size(); x++) {
                    if (outComing_goods.get(i).name_items.equals(list2.get(x).getC_name())) {
                        double price = Double.parseDouble(outComing_goods.get(i).number_item) * Double.parseDouble(list2.get(x).getC_supply_price());
                        price -= ((price / 100.0) * (Double.parseDouble(outComing_goods.get(i).discount)));
                        Out_Supply_Price += price;
                        
                        price = Double.parseDouble(outComing_goods.get(i).number_item) * Double.parseDouble(list2.get(x).getC_wholesale_price());
                        price -= ((price / 100.0) * (Double.parseDouble(outComing_goods.get(i).discount)));
                        Out_Wholesale_price += price;
                        
                        price = Double.parseDouble(outComing_goods.get(i).number_item) * Double.parseDouble(list2.get(x).getC_Consumer_selling_price());
                        price -= ((price / 100.0) * (Double.parseDouble(outComing_goods.get(i).discount)));
                        Out_Consumer_selling_price += price;
                        break;
                    }
                }
                mm.addRow(col);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                connection.close();
                preparedStatement.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }
    
    public void get_Current_goods(String search) {
        current_goods.clear();
        Current_Supply_Price = 0.0;
        Current_Wholesale_price = 0.0;
        Current_Consumer_selling_price = 0.0;
        Security security = new Security();
        try {
            connection = security.coneect();
            if (search.equals("(جميع الاصناف)")) {
                preparedStatement = connection.prepareStatement("SELECT * FROM current_goods WHERE Y_id = '" + Running.Y_id + "' order by name_items");
            } else {
                preparedStatement = connection.prepareStatement("SELECT * FROM current_goods WHERE Y_id = '" + Running.Y_id + "' and name_items = '" + search + "' order by name_items");
            }
            ResultSet set = preparedStatement.executeQuery();
            DefaultTableModel mm = (DefaultTableModel) jTable3.getModel();
            Object[] col = new Object[7];
            while (set.next()) {
                Data_current_goods d = new Data_current_goods(set.getString("name_items"), set.getString("In_items"), set.getString("Out_items"), set.getString("Current_items"), set.getString("price"), set.getString("total"));
                current_goods.add(d);
            }
            for (int i = 0; i < current_goods.size(); i++) {
                col[6] = i + 1;
                col[5] = current_goods.get(i).name_items;
                col[4] = current_goods.get(i).In_items;
                col[3] = current_goods.get(i).Out_items;
                col[2] = current_goods.get(i).Current_items;
                col[1] = current_goods.get(i).price;
                col[0] = current_goods.get(i).total;
                for (int x = 0; x < list2.size(); x++) {
                    if (current_goods.get(i).name_items.equals(list2.get(x).getC_name())) {
                        double price = Double.parseDouble(current_goods.get(i).Current_items) * Double.parseDouble(list2.get(x).getC_supply_price());
                        Current_Supply_Price += price;
                        
                        price = Double.parseDouble(current_goods.get(i).Current_items) * Double.parseDouble(list2.get(x).getC_wholesale_price());
                        Current_Wholesale_price += price;
                        
                        price = Double.parseDouble(current_goods.get(i).Current_items) * Double.parseDouble(list2.get(x).getC_Consumer_selling_price());
                        Current_Consumer_selling_price += price;
                        break;
                    }
                }
                mm.addRow(col);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                connection.close();
                preparedStatement.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }
    
    public void show_data2() {
        Security security = new Security();
        try {
            connection = security.coneect();
            preparedStatement = connection.prepareStatement("SELECT * FROM categories WHERE Y_id = '" + Running.Y_id + "' order by C_name");
            ResultSet set = preparedStatement.executeQuery();
            while (set.next()) {
                Data_Items_Card d1 = new Data_Items_Card(set.getString("C_id"), set.getString("C_name"), set.getString("C_supply_price"), set.getString("C_wholesale_price"), set.getString("C_Consumer_selling_price"));
                list2.add(d1);
            }
            items = new String[list2.size() + 1];
            items[0] = "(جميع الاصناف)";
            for (int i = 0; i < list2.size(); i++) {
                items[i + 1] = list2.get(i).getC_name();
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                connection.close();
                preparedStatement.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }
    
    public void table1() {
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "الاجمالي", "الخصم", "السعر", "العدد", "اسم الصنف", "الحركة", "فاتورة رقم", "من خلال", "بتاريخ", "م"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false, false, false, false
            };
            
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setMinWidth(50);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(3).setMinWidth(50);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(4).setMinWidth(180);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(180);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(180);
            jTable1.getColumnModel().getColumn(6).setMinWidth(50);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(9).setMinWidth(50);
            jTable1.getColumnModel().getColumn(9).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(9).setMaxWidth(50);
        }
    }
    
    public void table2() {
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "الاجمالي", "الخصم", "السعر", "العدد", "اسم الصنف", "الحركة", "فاتورة رقم", "الي حساب", "بتاريخ", "م"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false, false, false, false
            };
            
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTable2.setRowHeight(30);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(1).setMinWidth(50);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTable2.getColumnModel().getColumn(1).setMaxWidth(50);
            jTable2.getColumnModel().getColumn(3).setMinWidth(50);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTable2.getColumnModel().getColumn(3).setMaxWidth(50);
            jTable2.getColumnModel().getColumn(4).setMinWidth(180);
            jTable2.getColumnModel().getColumn(4).setPreferredWidth(180);
            jTable2.getColumnModel().getColumn(4).setMaxWidth(180);
            jTable2.getColumnModel().getColumn(6).setMinWidth(50);
            jTable2.getColumnModel().getColumn(6).setPreferredWidth(50);
            jTable2.getColumnModel().getColumn(6).setMaxWidth(50);
            jTable2.getColumnModel().getColumn(9).setMinWidth(50);
            jTable2.getColumnModel().getColumn(9).setPreferredWidth(50);
            jTable2.getColumnModel().getColumn(9).setMaxWidth(50);
        }
    }
    
    public void table3() {
        jTable3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "اجمالي القيمة", "السعر", "الباقي", "الخارج", "الداخل", "اسم الصنف", "م"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false
            };
            
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTable3.setRowHeight(30);
        jScrollPane3.setViewportView(jTable3);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
