/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package soli.plan.pkg1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DELL
 */
public class Jops extends javax.swing.JFrame {

    /**
     * Creates new form Jops
     */
    static Connection connection;
    static Statement statement;
    static PreparedStatement preparedStatement;
    ArrayList<Data_Jops> list1 = new ArrayList<>();
    ArrayList<Data_Jops> list2 = new ArrayList<>();
    ImageIcon j = new ImageIcon("E:\\Work\\Soli Plan 1\\src\\soli\\plan\\pkg1\\download13.png");
    ImageIcon j2 = new ImageIcon("E:\\Work\\Soli Plan 1\\src\\soli\\plan\\pkg1\\download12.png");
    boolean flag_lock = false;
    public int select_row = -1;
    public int mouse_click = 1;

    public Jops() {
        initComponents();
        this.setResizable(false);
        this.setLocation(50, 50);
        this.setDefaultCloseOperation(Jops.DO_NOTHING_ON_CLOSE);
        Show_data1();
        Show_data2();
        count.setText("0   /  " + list1.size() + "");
        int start = 0;
        if (list1.size() != 0) {
            start = Integer.parseInt((list1.get(list1.size() - 1).getJ_id()));
        }
        start += 1;
        Id.setText(start + "");
        if (Running.lock3.equals("1")) {
            jButton6.setIcon(j);
            flag_lock = true;
            Id.setEnabled(false);
            Name.setEnabled(false);
            Adderess.setEnabled(false);
            Jop.setEnabled(false);
            Vodavon.setEnabled(false);
            Etsalat.setEnabled(false);
            We.setEnabled(false);
            Nots.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Jop = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Adderess = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Vodavon = new javax.swing.JTextField();
        Etsalat = new javax.swing.JTextField();
        We = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Nots = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        count = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(65, 105, 225));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("قائمة الموظفين");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setPreferredSize(new java.awt.Dimension(155, 34));

        jPanel2.setBackground(new java.awt.Color(240, 128, 128));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("اسم الموظف :");

        Name.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Name.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Name.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("تعديل الأسم");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("كود الموظف :");

        Id.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Id.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Id.setToolTipText("");
        Id.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("وظفتة :");

        Jop.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Jop.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Jop.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("عنوانة :");

        Adderess.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Adderess.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Adderess.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("أرقام هواتفة :");

        Vodavon.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Vodavon.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Vodavon.setText("فودافون");
        Vodavon.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        Etsalat.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Etsalat.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Etsalat.setText("اتصالات");
        Etsalat.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        We.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        We.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        We.setText("وي");
        We.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("ملاحظات عنه :");

        Nots.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Nots.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Nots.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Adderess, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(We, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Etsalat, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Jop, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Vodavon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(Id)))
                    .addComponent(Nots))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6))
                    .addComponent(jLabel7))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Adderess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(We, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Etsalat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Vodavon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(240, 128, 128));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soli/plan/pkg1/download8.png"))); // NOI18N
        jButton2.setText("التالي");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soli/plan/pkg1/download9.png"))); // NOI18N
        jButton3.setText("السابق");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soli/plan/pkg1/download10.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soli/plan/pkg1/download11.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soli/plan/pkg1/download12.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        count.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        count.setForeground(new java.awt.Color(255, 255, 255));
        count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        count.setText("jLabel8");
        count.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(count, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(count, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("قائمة أبجدية للبحث عن موظف من خلال الكود");

        jTextField7.setBackground(new java.awt.Color(255, 255, 204));
        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField7KeyReleased(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(255, 255, 204));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setRowHeight(35);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        jTextField8.setBackground(new java.awt.Color(204, 255, 204));
        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("قائمة أبجدية للبحث عن موظف من خلال الاسم");

        jTable2.setBackground(new java.awt.Color(204, 255, 204));
        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setRowHeight(35);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(157, 157, 157)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int x1 = JOptionPane.showConfirmDialog(this, "are you want to delete this data!");
        if (x1 == 0) {
            if (Running.lock3.equals("0")) {
                Security security = new Security();
                try {
                    connection = security.coneect();
                    statement = connection.createStatement();
                    String query = "";
                    if (mouse_click == 1) {
                        query = "delete from Jops where J_id = '" + list1.get(select_row).getJ_id() + "'";
                    } else if (mouse_click == 2) {
                        query = "delete from Jops where J_id = '" + list2.get(select_row).getJ_id() + "'";
                    }
                    statement.executeUpdate(query);
                    new Jops().setVisible(true);
                    this.dispose();
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                } finally {
                    try {
                        connection.close();
                        statement.close();
                    } catch (Exception e) {
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Security security = new Security();
        try {
            connection = security.coneect();
            statement = connection.createStatement();
            if (flag_lock) {
                jButton6.setIcon(j2);
                flag_lock = false;
                Running.lock3 = "0";
                Id.setEnabled(true);
                Name.setEnabled(true);
                Adderess.setEnabled(true);
                Jop.setEnabled(true);
                Vodavon.setEnabled(true);
                Etsalat.setEnabled(true);
                We.setEnabled(true);
                Nots.setEnabled(true);
            } else {
                jButton6.setIcon(j);
                flag_lock = true;
                Running.lock3 = "1";
                Id.setEnabled(false);
                Name.setEnabled(false);
                Adderess.setEnabled(false);
                Jop.setEnabled(false);
                Vodavon.setEnabled(false);
                Etsalat.setEnabled(false);
                We.setEnabled(false);
                Nots.setEnabled(false);
            }
            String quere = "update years set Y_lock3 = '" + Running.lock3 + "' where Y_id = '" + Running.Y_id + "'";
            statement.execute(quere);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                connection.close();
                statement.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Security security = new Security();
        try {
            connection = security.coneect();
            statement = connection.createStatement();
            String id = Id.getText();
            String name = Name.getText();
            String jop = Jop.getText();
            String address = Adderess.getText();
            String vodavon = Vodavon.getText();
            String etsalat = Etsalat.getText();
            String we = We.getText();
            String nots = Nots.getText();
            if (id.isEmpty() || name.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Enter Correct Format.");
            } else {
                String quere = "";
                if (id.equals("1") && !Running.Y_id.equals("1")) {
                    quere = "insert into Jops set J_name = '" + name + "', J_jop = '" + jop + "', J_address = '" + address + "', J_vodavon = '" + vodavon + "', J_etsalat = '" + etsalat + "', J_we = '" + we + "', J_nots = '" + nots + "', Y_id = '" + Running.Y_id + "'";
                } else {
                    quere = "insert into Jops values('" + id + "','" + name + "','" + jop + "','" + address + "','" + vodavon + "','" + etsalat + "','" + we + "','" + nots + "','" + Running.Y_id + "')";
                }
                statement.execute(quere);
                JOptionPane.showMessageDialog(this, "Data Inserted.");
                new Jops().setVisible(true);
                this.dispose();
            }
        } catch (Exception e) {
            if (Running.lock3 == "0") {
                String quere = "update Jops set J_name = '" + Name.getText() + "', J_jop = '" + Jop.getText() + "', J_address = '" + Adderess.getText() + "', J_vodavon = '" + Vodavon.getText() + "', J_etsalat = '" + Etsalat.getText() + "', J_we = '" + We.getText() + "', J_nots = '" + Nots.getText() + "' where J_id = '" + Id.getText() + "'";
                try {
                    statement.execute(quere);
                    new Jops().setVisible(true);
                    this.dispose();
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }
            }
        } finally {
            try {
                connection.close();
                statement.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        mouse_click = 2;
        select_row = jTable2.getSelectedRow();
        String Search = jTable2.getValueAt(select_row, 0).toString();
        for (int i = 0; i < list2.size(); i++) {
            if (list2.get(i).getJ_name().equals(Search)) {
                select_row = i;
                break;
            }
        }
        Id.setText(list2.get(select_row).getJ_id());
        Name.setText(list2.get(select_row).getJ_name());
        Adderess.setText(list2.get(select_row).getJ_address());
        Jop.setText(list2.get(select_row).getJ_jop());
        Vodavon.setText(list2.get(select_row).getJ_vodavon());
        Etsalat.setText(list2.get(select_row).getJ_etsalat());
        We.setText(list2.get(select_row).getJ_we());
        Nots.setText(list2.get(select_row).getJ_nots());
        count.setText(select_row + 1 + "   /  " + list2.size() + "");
        jTable2.clearSelection();
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        mouse_click = 1;
        select_row = jTable1.getSelectedRow();
        String Search = jTable1.getValueAt(select_row, 0).toString();
        for (int i = 0; i < list1.size(); i++) {
            if (list1.get(i).getJ_id().equals(Search)) {
                select_row = i;
                break;
            }
        }
        Id.setText(list1.get(select_row).getJ_id());
        Name.setText(list1.get(select_row).getJ_name());
        Adderess.setText(list1.get(select_row).getJ_address());
        Jop.setText(list1.get(select_row).getJ_jop());
        Vodavon.setText(list1.get(select_row).getJ_vodavon());
        Etsalat.setText(list1.get(select_row).getJ_etsalat());
        We.setText(list1.get(select_row).getJ_we());
        Nots.setText(list1.get(select_row).getJ_nots());
        count.setText(select_row + 1 + "   /  " + list1.size() + "");
        jTable1.clearSelection();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyReleased
        DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
        String search = jTextField7.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_jTextField7KeyReleased

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        DefaultTableModel table = (DefaultTableModel) jTable2.getModel();
        String search = jTextField8.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        jTable2.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_jTextField8KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (Running.lock3.equals("0")) {
            Security security = new Security();
            try {
                connection = security.coneect();
                statement = connection.createStatement();
                String quere = "update Jops set J_name = '" + Name.getText() + "' where J_id = '" + Id.getText() + "'";
                statement.execute(quere);
                JOptionPane.showMessageDialog(this, "Name Updated.");
                new Jops().setVisible(true);
                this.dispose();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            } finally {
                try {
                    connection.close();
                    preparedStatement.close();
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (mouse_click == 1) {
            if (select_row + 1 < list1.size()) {
                select_row++;
                Id.setText(list1.get(select_row).getJ_id());
                Name.setText(list1.get(select_row).getJ_name());
                Adderess.setText(list1.get(select_row).getJ_address());
                Jop.setText(list1.get(select_row).getJ_jop());
                Vodavon.setText(list1.get(select_row).getJ_vodavon());
                Etsalat.setText(list1.get(select_row).getJ_etsalat());
                We.setText(list1.get(select_row).getJ_we());
                Nots.setText(list1.get(select_row).getJ_nots());
                count.setText(select_row + 1 + "   /  " + list1.size() + "");
            }
        } else if (mouse_click == 2) {
            if (select_row + 1 < list2.size()) {
                select_row++;
                Id.setText(list2.get(select_row).getJ_id());
                Name.setText(list2.get(select_row).getJ_name());
                Adderess.setText(list2.get(select_row).getJ_address());
                Jop.setText(list2.get(select_row).getJ_jop());
                Vodavon.setText(list2.get(select_row).getJ_vodavon());
                Etsalat.setText(list2.get(select_row).getJ_etsalat());
                We.setText(list2.get(select_row).getJ_we());
                Nots.setText(list2.get(select_row).getJ_nots());
                count.setText(select_row + 1 + "   /  " + list2.size() + "");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (mouse_click == 1) {
            if (select_row - 1 >= 0) {
                select_row--;
                Id.setText(list1.get(select_row).getJ_id());
                Name.setText(list1.get(select_row).getJ_name());
                Adderess.setText(list1.get(select_row).getJ_address());
                Jop.setText(list1.get(select_row).getJ_jop());
                Vodavon.setText(list1.get(select_row).getJ_vodavon());
                Etsalat.setText(list1.get(select_row).getJ_etsalat());
                We.setText(list1.get(select_row).getJ_we());
                Nots.setText(list1.get(select_row).getJ_nots());
                count.setText(select_row + 1 + "   /  " + list1.size() + "");
            }
        } else if (mouse_click == 2) {
            if (select_row - 1 >= 0) {
                select_row--;
                Id.setText(list2.get(select_row).getJ_id());
                Name.setText(list2.get(select_row).getJ_name());
                Adderess.setText(list2.get(select_row).getJ_address());
                Jop.setText(list2.get(select_row).getJ_jop());
                Vodavon.setText(list2.get(select_row).getJ_vodavon());
                Etsalat.setText(list2.get(select_row).getJ_etsalat());
                We.setText(list2.get(select_row).getJ_we());
                Nots.setText(list2.get(select_row).getJ_nots());
                count.setText(select_row + 1 + "   /  " + list2.size() + "");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    public void Show_data1() {
        Security security = new Security();
        try {
            connection = security.coneect();
            preparedStatement = connection.prepareStatement("SELECT * FROM Jops WHERE Y_id = '" + Running.Y_id + "' order by J_id");
            ResultSet set = preparedStatement.executeQuery();
            DefaultTableModel mm = (DefaultTableModel) jTable1.getModel();
            Object[] col = new Object[1];
            while (set.next()) {
                Data_Jops d1 = new Data_Jops(set.getString("J_id"), set.getString("J_name"), set.getString("J_jop"), set.getString("J_address"), set.getString("J_vodavon"), set.getString("J_etsalat"), set.getString("J_we"), set.getString("J_nots"));
                list1.add(d1);
            }
            for (int i = 0; i < list1.size(); i++) {
                col[0] = list1.get(i).getJ_id();
                mm.addRow(col);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                connection.close();
                preparedStatement.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }

    public void Show_data2() {
        Security security = new Security();
        try {
            connection = security.coneect();
            preparedStatement = connection.prepareStatement("SELECT * FROM Jops WHERE Y_id = '" + Running.Y_id + "' order by J_name");
            ResultSet set = preparedStatement.executeQuery();
            DefaultTableModel mm = (DefaultTableModel) jTable2.getModel();
            Object[] col = new Object[1];
            while (set.next()) {
                Data_Jops d1 = new Data_Jops(set.getString("J_id"), set.getString("J_name"), set.getString("J_jop"), set.getString("J_address"), set.getString("J_vodavon"), set.getString("J_etsalat"), set.getString("J_we"), set.getString("J_nots"));
                list2.add(d1);
            }
            for (int i = 0; i < list2.size(); i++) {
                col[0] = list2.get(i).getJ_name();
                mm.addRow(col);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                connection.close();
                preparedStatement.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jops().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Adderess;
    private javax.swing.JTextField Etsalat;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Jop;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Nots;
    private javax.swing.JTextField Vodavon;
    private javax.swing.JTextField We;
    private javax.swing.JLabel count;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
