/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package soli.plan.pkg1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author DELL
 */
public class Setting extends javax.swing.JFrame {

    static Connection connection;
    static Statement statement;
    static PreparedStatement preparedStatement;
    ArrayList<Data_Items_Card> list1 = new ArrayList<>();
    ArrayList<Data_Suppliers_Customers> list2 = new ArrayList<>();
    ArrayList<Data_Suppliers_Customers> list3 = new ArrayList<>();
    double mony = 0.0;
    String stt = "";

    public Setting() {
        initComponents();
        this.setResizable(false);
        this.setLocation(400, 115);
        this.setDefaultCloseOperation(Setting.DO_NOTHING_ON_CLOSE);
        SimpleDateFormat date = new SimpleDateFormat("YYYY");
        Date dat = new Date();
        jLabel2.setText(date.format(dat).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("خصائص ضبط عام");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 58)); // NOI18N
        jLabel2.setText("2022");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 51, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("         كارتة الأصناف");

        jRadioButton1.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButton1.setText("اجعل كارتة الأصناف جديدة تماما (خالية من جميع بنود الأصناف)");

        jRadioButton4.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButton4.setText("انسخ كارتة الأصناف الخاصة بالعام الماضي الي العام الحالي");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(44, 44, 44)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 51, 0));
        jLabel5.setText("قائمة الموردين و العملاء");

        jRadioButton3.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButton3.setText("اجعل قائمة الموردين و العملاء جديدة تماما");

        jRadioButton2.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButton2.setText("انسخ قائمة الموردين و العملاء الخاصة بالعام الماضي الي العام الحالي");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(215, 215, 215))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addGap(12, 12, 12)
                .addComponent(jRadioButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("  Project manager :- Soliman Mahmoud Soliman               Phone :- 01028721772");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soli/plan/pkg1/download 4.png"))); // NOI18N
        jButton2.setText("تراحع عن تطبيق تلك الخصائص");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("E:\\Work\\download3.png")); // NOI18N
        jButton1.setText("قم بتطبيق تلك الخصائص");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Running().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Security security = new Security();
        try {
            connection = security.coneect();
            statement = connection.createStatement();
            String quere;
            quere = "insert into years set Y_name = '" + jLabel2.getText().toString() + "', Y_lock = 1,Y_lock2=1,Y_lock3 =1,Y_lock4=1,Y_lock5=1,Y_lock6=1";
            statement.execute(quere);
            if (jRadioButton4.isSelected()) {
                preparedStatement = connection.prepareStatement("SELECT Y_id FROM years WHERE Y_name = '" + (Integer.parseInt(jLabel2.getText().toString()) - 1) + "'");
                ResultSet set = preparedStatement.executeQuery();
                set.next();
                int id = Integer.parseInt(set.getString("Y_id"));
                preparedStatement = connection.prepareStatement("SELECT * FROM categories WHERE Y_id = '" + id + "'");
                ResultSet set1 = preparedStatement.executeQuery();
                while (set1.next()) {
                    Data_Items_Card d1 = new Data_Items_Card(set1.getString("C_id"), set1.getString("C_name"), set1.getString("C_supply_price"), set1.getString("C_wholesale_price"), set1.getString("C_Consumer_selling_price"));
                    list1.add(d1);
                }
                for (int i = 0; i < list1.size(); i++) {
                    quere = "insert into categories set C_name = '" + list1.get(i).getC_name() + "', C_supply_price ='" + list1.get(i).getC_supply_price() + "', C_wholesale_price = '" + list1.get(i).getC_wholesale_price() + "', C_Consumer_selling_price = '" + list1.get(i).getC_Consumer_selling_price() + "', Y_id = '" + (id + 1) + "'";
                    statement.execute(quere);
                }
            }
            if (jRadioButton2.isSelected()) {
                preparedStatement = connection.prepareStatement("SELECT Y_id FROM years WHERE Y_name = '" + (Integer.parseInt(jLabel2.getText().toString()) - 1) + "'");
                ResultSet set = preparedStatement.executeQuery();
                set.next();
                int id = Integer.parseInt(set.getString("Y_id"));
                preparedStatement = connection.prepareStatement("SELECT * FROM suppliers WHERE Y_id = '" + id + "'");
                ResultSet set1 = preparedStatement.executeQuery();
                while (set1.next()) {
                    Data_Suppliers_Customers d1 = new Data_Suppliers_Customers(set1.getString("S_id"), set1.getString("S_name"), set1.getString("S_address"), set1.getString("den"), set1.getString("state_den"));
                    list2.add(d1);
                }
                for (int i = 0; i < list2.size(); i++) {
                    S_den(list2.get(i).getS_name(), id, list2.get(i).getState_den(), Double.parseDouble(list2.get(i).getDen()));
                    quere = "insert into suppliers set S_name = '" + list2.get(i).getS_name() + "', S_addres ='" + list2.get(i).getS_address() + "', Y_id = '" + (id + 1) + "', den = '" + mony + "', state_den = '" + stt + "'";
                    statement.execute(quere);
                }
                preparedStatement = connection.prepareStatement("SELECT * FROM customers WHERE Y_id = '" + id + "'");
                ResultSet set2 = preparedStatement.executeQuery();
                while (set2.next()) {
                    Data_Suppliers_Customers d1 = new Data_Suppliers_Customers(set2.getString("C_id"), set2.getString("C_name"), set2.getString("C_address"), set2.getString("C_den"), set2.getString("C_state_den"), 0);
                    list3.add(d1);
                }
                for (int i = 0; i < list3.size(); i++) {
                    C_den(list3.get(i).getC_name(), id, list3.get(i).getC_state_den(), Double.parseDouble(list3.get(i).getC_den()));
                    quere = "insert into customers set C_name = '" + list3.get(i).getC_name() + "', C_addres ='" + list3.get(i).getC_address() + "', Y_id = '" + (id + 1) + "', C_den = '" + mony + "', C_state_den = '" + stt + "'";
                    statement.execute(quere);
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                connection.close();
                statement.close();
                preparedStatement.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void C_den(String name, int id, String state, double den) {
        Security security = new Security();
        try {
            connection = security.coneect();
            preparedStatement = connection.prepareStatement("SELECT * from bills where name = '" + name + "' and Y_id = '" + id + "'");
            ResultSet set = preparedStatement.executeQuery();
            double x = 0.0;
            while (set.next()) {
                if (Double.parseDouble(set.getString("Total_after_discount")) != 0.0) {
                    if (!set.getString("nots").equals("مرتجع")) {
                        x += Double.parseDouble(set.getString("total")) - (Double.parseDouble(set.getString("total")) / Double.parseDouble(set.getString("Total_after_discount")));
                    } else {
                        x -= Double.parseDouble(set.getString("total")) - (Double.parseDouble(set.getString("total")) / Double.parseDouble(set.getString("Total_after_discount")));
                    }
                } else {
                    if (!set.getString("nots").equals("مرتجع")) {
                        x += Double.parseDouble(set.getString("total"));
                    } else {
                        x -= Double.parseDouble(set.getString("total"));
                    }
                }
            }
            preparedStatement = connection.prepareStatement("select * from instore where Y_id = '" + id + "' and nots = '" + name + "' ");
            ResultSet set2 = preparedStatement.executeQuery();
            double x2 = 0.0;
            while (set2.next()) {
                x2 += Double.parseDouble(set2.getString("mony"));
            }
            if (x > x2) {
                if (state.equals("عليه")) {
                    mony = (x - x2) + den; // عليه
                } else {
                    mony = (x - x2) - den; // عليه
                }
                stt = "عليه";
            } else {
                if (state.equals("عليه")) {
                    mony = (x2 - x) - den; // له
                } else {
                    mony = (x2 - x) + den; // له
                }
                stt = "له";
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                connection.close();
                preparedStatement.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }

    public void S_den(String name, int id, String state, double den) {
        Security security = new Security();
        try {
            connection = security.coneect();
            preparedStatement = connection.prepareStatement("SELECT * from bills where name = '" + name + "' and Y_id = '" + id + "'");
            ResultSet set = preparedStatement.executeQuery();
            double x = 0.0;
            while (set.next()) {
                if (Double.parseDouble(set.getString("Total_after_discount")) != 0.0) {
                    if (!set.getString("nots").equals("مرتجع")) {
                        x += Double.parseDouble(set.getString("total")) - (Double.parseDouble(set.getString("total")) / Double.parseDouble(set.getString("Total_after_discount")));
                    } else {
                        x -= Double.parseDouble(set.getString("total")) - (Double.parseDouble(set.getString("total")) / Double.parseDouble(set.getString("Total_after_discount")));
                    }
                } else {
                    if (!set.getString("nots").equals("مرتجع")) {
                        x += Double.parseDouble(set.getString("total"));
                    } else {
                        x -= Double.parseDouble(set.getString("total"));
                    }
                }
            }
            preparedStatement = connection.prepareStatement("select * from outstore where Y_id = '" + id + "' and nots = '" + name + "'");
            ResultSet set2 = preparedStatement.executeQuery();
            double x2 = 0.0;
            while (set2.next()) {
                x2 += Double.parseDouble(set2.getString("mony"));
            }
            if (x > x2) {
                if (state.equals("له")) {
                    mony = (x - x2) + den; // له
                } else {
                    mony = (x - x2) - den; // له
                }
                stt = "له";
            } else {
                if (state.equals("عليه")) {
                    mony = (x2 - x) + den; // عليه
                } else {
                    mony = (x2 - x) - den; // عليه
                }
                stt = "عليه";
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                connection.close();
                preparedStatement.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setting.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setting.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setting.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setting.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Setting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
}
