/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package soli.plan.pkg1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Store extends javax.swing.JFrame {

    /**
     * Creates new form Store
     */
    ArrayList<Data_Suppliers_Customers> list1 = new ArrayList<>();
    ArrayList<Data_Suppliers_Customers> list2 = new ArrayList<>();
    ArrayList<Data_Jops> list3 = new ArrayList<>();
    ArrayList<Data_StateStore> list4 = new ArrayList<>();
    ArrayList<Date_InStore> list5 = new ArrayList<>();
    ArrayList<Date_InStore> list6 = new ArrayList<>();
    ArrayList<Data_AllStore> list7 = new ArrayList<>();

    ImageIcon j = new ImageIcon("E:\\Work\\Soli Plan 1\\src\\soli\\plan\\pkg1\\download13.png");
    ImageIcon j2 = new ImageIcon("E:\\Work\\Soli Plan 1\\src\\soli\\plan\\pkg1\\download12.png");

    static Connection connection;
    static Statement statement;
    static PreparedStatement preparedStatement;
    boolean flag_lock = false;
    boolean flag_lock2 = false;
    public int select_row = -1;
    public int select_row2 = -1;
    public double in_mony = 0;
    public double out_mony = 0;

    public Store() {
        initComponents();
        this.setResizable(false);
        this.setLocation(100, 50);
        this.setDefaultCloseOperation(Store.DO_NOTHING_ON_CLOSE);
        Get_data_suppliers();
        Get_data_customers();
        Get_data_jops();
        Get_date_state();
        show_data1();
        Show_date2();
        String[] s = new String[list1.size()];
        for (int i = 0; i < list1.size(); i++) {
            s[i] = list1.get(i).getS_name().toString();
        }
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(s));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(s));
        if (Running.lock4.equals("1")) {
            jButton18.setIcon(j);
            flag_lock = true;
            jTextField9.setEnabled(false);
            jTextField10.setEnabled(false);
            jTextField11.setEnabled(false);
            jTextField12.setEnabled(false);
            jComboBox4.setEnabled(false);
            jComboBox6.setEnabled(false);
        }
        if (Running.lock5.equals("1")) {
            jButton12.setIcon(j);
            flag_lock2 = true;
            jTextField5.setEnabled(false);
            jTextField6.setEnabled(false);
            jTextField7.setEnabled(false);
            jTextField8.setEnabled(false);
            jComboBox3.setEnabled(false);
            jComboBox5.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(65, 105, 225));

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(65, 105, 225));

        jTable1.setBackground(new java.awt.Color(255, 255, 204));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "تفصيل", "من حساب", "المبلغ", "بتاريخ", "م"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(35);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel6.setBackground(new java.awt.Color(240, 128, 128));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("بتاريخ : ");

        jTextField9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField9.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jTextField10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField10.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jTextField11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField11.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jButton14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton14.setText("تاريخ اليوم");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("قيمة المبلغ : ");

        jTextField12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField12.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jComboBox4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "مورد", "عميل", "موظف", "ايرادات أخري" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("من حساب : ");

        jComboBox6.setEditable(true);
        jComboBox6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jComboBox6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox6KeyReleased(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soli/plan/pkg1/download8.png"))); // NOI18N
        jButton15.setText("التالي");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soli/plan/pkg1/download9.png"))); // NOI18N
        jButton16.setText("السابق");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soli/plan/pkg1/download10.png"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soli/plan/pkg1/download12.png"))); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soli/plan/pkg1/download11.png"))); // NOI18N
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Work\\safe.png")); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton19)
                        .addGap(113, 113, 113)
                        .addComponent(jButton18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton17))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton16)
                        .addGap(18, 18, 18)
                        .addComponent(jButton15)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addContainerGap(18, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton18)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton15)
                                    .addComponent(jButton16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton17)
                                    .addComponent(jButton19))))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(4, 4, 4))))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("داخل الي الخزينة", jPanel3);

        jPanel4.setBackground(new java.awt.Color(65, 105, 225));

        jPanel5.setBackground(new java.awt.Color(240, 128, 128));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("بتاريخ : ");

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField5.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField6.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField7.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton8.setText("تاريخ اليوم");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("قيمة المبلغ : ");

        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField8.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "مورد", "عميل", "موظف", "مصاريف أخري" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("الي حساب :");

        jComboBox5.setEditable(true);
        jComboBox5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soli/plan/pkg1/download8.png"))); // NOI18N
        jButton9.setText("التالي");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soli/plan/pkg1/download9.png"))); // NOI18N
        jButton10.setText("السابق");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soli/plan/pkg1/download10.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soli/plan/pkg1/download12.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soli/plan/pkg1/download11.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\Work\\safe.png")); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton9))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jButton13)
                                .addGap(109, 109, 109)
                                .addComponent(jButton12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton11)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9)
                            .addComponent(jButton10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton11)
                            .addComponent(jButton12)
                            .addComponent(jButton13))))
                .addGap(16, 16, 16))
        );

        jTable2.setBackground(new java.awt.Color(204, 255, 204));
        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "تفصيل", "الي حساب", "المبلغ", "بتاريخ", "م"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setRowHeight(35);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("خارج من الخزينة", jPanel4);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("تقارير حركة الداخل و الخارج من الخزينة");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        SimpleDateFormat years = new SimpleDateFormat("YYYY");
        SimpleDateFormat month = new SimpleDateFormat("MM");
        SimpleDateFormat day = new SimpleDateFormat("dd");
        Date date = new Date();
        jTextField11.setText(years.format(date));
        jTextField10.setText(month.format(date));
        jTextField9.setText(day.format(date));
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        String[] s = null;
        if (jComboBox4.getSelectedItem().equals("مورد")) {
            s = new String[list1.size()];
            for (int i = 0; i < list1.size(); i++) {
                s[i] = list1.get(i).getS_name().toString();
            }
        } else if (jComboBox4.getSelectedItem().equals("عميل")) {
            s = new String[list2.size()];
            for (int i = 0; i < list2.size(); i++) {
                s[i] = list2.get(i).getC_name().toString();
            }
        } else if (jComboBox4.getSelectedItem().equals("موظف")) {
            s = new String[list3.size()];
            for (int i = 0; i < list3.size(); i++) {
                s[i] = list3.get(i).getJ_name().toString();
            }
        } else if (jComboBox4.getSelectedItem().equals("ايرادات أخري")) {
            s = new String[list4.size()];
            for (int i = 0; i < list4.size(); i++) {
                s[i] = list4.get(i).getState().toString();
            }
        }
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(s));
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox6KeyReleased

    }//GEN-LAST:event_jComboBox6KeyReleased

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        boolean in = false;
        Security security = new Security();
        try {
            connection = security.coneect();
            statement = connection.createStatement();
            String date = "";
            date = jTextField11.getText();
            date = date + "/" + jTextField10.getText();
            date = date + "/" + jTextField9.getText();
            String mony = jTextField12.getText();
            String state = jComboBox4.getSelectedItem().toString();
            if (mony.isEmpty() || date.equals("//")) {
                JOptionPane.showMessageDialog(this, "Please Enter Correct Format.");
            } else {
                if (state.equals("ايرادات أخري")) {
                    String search = jComboBox6.getSelectedItem().toString();
                    for (int i = 0; i < list4.size(); i++) {
                        if (list4.get(i).getState().equals(search)) {
                            String quere = "insert into instore set dat = '" + date + "', mony = '" + mony + "', state = '" + state + "', nots = '" + search + "', Y_id = '" + Running.Y_id + "'";
                            statement.execute(quere);
                            in = true;
                            break;
                        }
                    }
                    if (in == false) {
                        String quere = "insert into instore set dat = '" + date + "', mony = '" + mony + "', state = '" + state + "', nots = '" + search + "', Y_id = '" + Running.Y_id + "'";
                        statement.execute(quere);
                        String quer = "insert into statestore set state = '" + search + "'";
                        statement.execute(quer);
                    }
                } else {
                    String que = "insert into instore set dat = '" + date + "', mony = '" + mony + "', state = '" + state + "', nots = '" + jComboBox6.getSelectedItem().toString() + "', Y_id = '" + Running.Y_id + "'";
                    statement.execute(que);
                }
                preparedStatement = connection.prepareStatement("SELECT * FROM allstore WHERE dat = '" + date + "' and Y_id = '" + Running.Y_id + "'");
                ResultSet set = preparedStatement.executeQuery();
                while (set.next()) {
                    Data_AllStore d1 = new Data_AllStore(set.getString("dat"), set.getString("in_mony"), set.getString("out_mony"));
                    list7.add(d1);
                }
                if (list7.size() == 0) {
                    String que = "insert into allstore set dat = '" + date + "', in_mony = '" + mony + "', out_mony = '" + out_mony + "', Y_id = '" + Running.Y_id + "'";
                    statement.execute(que);
                } else {
                    in_mony = Double.parseDouble(mony) + Double.parseDouble(list7.get(0).getIn_mony().toString());
                    out_mony = Double.parseDouble(list7.get(0).getOut_mony().toString());
                    String quere = "update allstore set in_mony = '" + in_mony + "', out_mony = '" + out_mony + "' where dat = '" + date + "'";
                    statement.execute(quere);
                }
                new Store().setVisible(true);
                this.dispose();
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                connection.close();
                statement.close();
                preparedStatement.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        Security security = new Security();
        try {
            connection = security.coneect();
            statement = connection.createStatement();
            if (flag_lock) {
                jButton18.setIcon(j2);
                flag_lock = false;
                Running.lock4 = "0";
                jTextField9.setEnabled(true);
                jTextField10.setEnabled(true);
                jTextField11.setEnabled(true);
                jTextField12.setEnabled(true);
                jComboBox4.setEnabled(true);
                jComboBox6.setEnabled(true);
            } else {
                jButton18.setIcon(j);
                flag_lock = true;
                Running.lock4 = "1";
                jTextField9.setEnabled(false);
                jTextField10.setEnabled(false);
                jTextField11.setEnabled(false);
                jTextField12.setEnabled(false);
                jComboBox4.setEnabled(false);
                jComboBox6.setEnabled(false);
            }
            String quere = "update years set Y_lock4 = '" + Running.lock4 + "' where Y_id = '" + Running.Y_id + "'";
            statement.execute(quere);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                connection.close();
                statement.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        int x1 = JOptionPane.showConfirmDialog(this, "are you want to delete this data!");
        if (x1 == 0) {
            if (Running.lock4.equals("0")) {
                Security security = new Security();
                try {
                    connection = security.coneect();
                    statement = connection.createStatement();
                    String query = "delete from instore where id = '" + list5.get(select_row).getId() + "'";
                    statement.executeUpdate(query);
                    preparedStatement = connection.prepareStatement("SELECT * FROM allstore WHERE dat = '" + list5.get(select_row).getDat() + "'");
                    ResultSet set = preparedStatement.executeQuery();
                    while (set.next()) {
                        Data_AllStore d1 = new Data_AllStore(set.getString("dat"), set.getString("in_mony"), set.getString("out_mony"));
                        list7.add(d1);
                    }
                    in_mony = Double.parseDouble(list7.get(0).getIn_mony().toString()) - Double.parseDouble(list5.get(select_row).getMony());
                    if (in_mony < 0) {
                        in_mony = 0;
                    }
                    if (in_mony == 0 && Double.parseDouble(list7.get(0).getOut_mony().toString()) == 0) {
                        String quere = "delete from allstore where dat = '" + list5.get(select_row).getDat() + "'";
                        statement.execute(quere);
                    } else {
                        String quere = "update allstore set in_mony = '" + in_mony + "' where dat = '" + list5.get(select_row).getDat() + "'";
                        statement.execute(quere);
                    }
                    new Store().setVisible(true);
                    this.dispose();
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                } finally {
                    try {
                        connection.close();
                        statement.close();
                        preparedStatement.close();
                    } catch (Exception e) {
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please, Open the lock bafore delete!");
            }
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        select_row = jTable1.getSelectedRow();
        String date = list5.get(select_row).getDat();
        jTextField9.setText(date.substring(8, 10));
        jTextField10.setText(date.substring(5, 7));
        jTextField11.setText(date.substring(0, 4));
        jTextField12.setText(list5.get(select_row).getMony());
        jComboBox4.setSelectedItem(list5.get(select_row).getState());
        jComboBox6.setSelectedItem(list5.get(select_row).getNots());
        jTable1.clearSelection();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        if (select_row + 1 < list5.size()) {
            select_row++;
            String date = list5.get(select_row).getDat();
            jTextField9.setText(date.substring(8, 10));
            jTextField10.setText(date.substring(5, 7));
            jTextField11.setText(date.substring(0, 4));
            jTextField12.setText(list5.get(select_row).getMony());
            jComboBox4.setSelectedItem(list5.get(select_row).getState());
            jComboBox6.setSelectedItem(list5.get(select_row).getNots());
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        if (select_row - 1 >= 0) {
            select_row--;
            String date = list5.get(select_row).getDat();
            jTextField9.setText(date.substring(8, 10));
            jTextField10.setText(date.substring(5, 7));
            jTextField11.setText(date.substring(0, 4));
            jTextField12.setText(list5.get(select_row).getMony());
            jComboBox4.setSelectedItem(list5.get(select_row).getState());
            jComboBox6.setSelectedItem(list5.get(select_row).getNots());
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        SimpleDateFormat years = new SimpleDateFormat("YYYY");
        SimpleDateFormat month = new SimpleDateFormat("MM");
        SimpleDateFormat day = new SimpleDateFormat("dd");
        Date date = new Date();
        jTextField7.setText(years.format(date));
        jTextField6.setText(month.format(date));
        jTextField5.setText(day.format(date));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        String[] s = null;
        if (jComboBox3.getSelectedItem().equals("مورد")) {
            s = new String[list1.size()];
            for (int i = 0; i < list1.size(); i++) {
                s[i] = list1.get(i).getS_name().toString();
            }
        } else if (jComboBox3.getSelectedItem().equals("عميل")) {
            s = new String[list2.size()];
            for (int i = 0; i < list2.size(); i++) {
                s[i] = list2.get(i).getC_name().toString();
            }
        } else if (jComboBox3.getSelectedItem().equals("موظف")) {
            s = new String[list3.size()];
            for (int i = 0; i < list3.size(); i++) {
                s[i] = list3.get(i).getJ_name().toString();
            }
        } else if (jComboBox3.getSelectedItem().equals("مصاريف أخري")) {
            s = new String[list4.size()];
            for (int i = 0; i < list4.size(); i++) {
                s[i] = list4.get(i).getState().toString();
            }
        }
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(s));
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        boolean in = false;
        Security security = new Security();
        try {
            connection = security.coneect();
            statement = connection.createStatement();
            String date = "";
            date = jTextField7.getText();
            date = date + "/" + jTextField6.getText();
            date = date + "/" + jTextField5.getText();
            String mony = jTextField8.getText();
            String state = jComboBox3.getSelectedItem().toString();
            if (mony.isEmpty() || date.equals("//")) {
                JOptionPane.showMessageDialog(this, "Please Enter Correct Format.");
            } else {
                if (state.equals("مصاريف أخري")) {
                    String search = jComboBox5.getSelectedItem().toString();
                    for (int i = 0; i < list4.size(); i++) {
                        if (list4.get(i).getState().equals(search)) {
                            String quere = "insert into outstore set dat = '" + date + "', mony = '" + mony + "', state = '" + state + "', nots = '" + search + "', Y_id = '" + Running.Y_id + "'";
                            statement.execute(quere);
                            in = true;
                            break;
                        }
                    }
                    if (in == false) {
                        String quere = "insert into outstore set dat = '" + date + "', mony = '" + mony + "', state = '" + state + "', nots = '" + search + "', Y_id = '" + Running.Y_id + "'";
                        statement.execute(quere);
                        String quer = "insert into statestore set state = '" + search + "'";
                        statement.execute(quer);
                    }
                } else {
                    String que = "insert into outstore set dat = '" + date + "', mony = '" + mony + "', state = '" + state + "', nots = '" + jComboBox5.getSelectedItem().toString() + "', Y_id = '" + Running.Y_id + "'";
                    statement.execute(que);
                }
                preparedStatement = connection.prepareStatement("SELECT * FROM allstore WHERE dat = '" + date + "' and Y_id = '" + Running.Y_id + "'");
                ResultSet set = preparedStatement.executeQuery();
                while (set.next()) {
                    Data_AllStore d1 = new Data_AllStore(set.getString("dat"), set.getString("in_mony"), set.getString("out_mony"));
                    list7.add(d1);
                }
                if (list7.size() == 0) {
                    String que = "insert into allstore set dat = '" + date + "', in_mony = '" + in_mony + "', out_mony = '" + mony + "', Y_id = '" + Running.Y_id + "'";
                    statement.execute(que);
                } else {
                    in_mony = Double.parseDouble(list7.get(0).getIn_mony().toString());
                    out_mony = Double.parseDouble(mony) + Double.parseDouble(list7.get(0).getOut_mony().toString());
                    String quere = "update allstore set in_mony = '" + in_mony + "', out_mony = '" + out_mony + "' where dat = '" + date + "'";
                    statement.execute(quere);
                }
                new Store().setVisible(true);
                this.dispose();
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                connection.close();
                statement.close();
                preparedStatement.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Security security = new Security();
        try {
            connection = security.coneect();
            statement = connection.createStatement();
            if (flag_lock2) {
                jButton12.setIcon(j2);
                flag_lock2 = false;
                Running.lock5 = "0";
                jTextField5.setEnabled(true);
                jTextField6.setEnabled(true);
                jTextField7.setEnabled(true);
                jTextField8.setEnabled(true);
                jComboBox3.setEnabled(true);
                jComboBox5.setEnabled(true);
            } else {
                jButton12.setIcon(j);
                flag_lock2 = true;
                Running.lock5 = "1";
                jTextField5.setEnabled(false);
                jTextField6.setEnabled(false);
                jTextField7.setEnabled(false);
                jTextField8.setEnabled(false);
                jComboBox3.setEnabled(false);
                jComboBox5.setEnabled(false);
            }
            String quere = "update years set Y_lock5 = '" + Running.lock5 + "' where Y_id = '" + Running.Y_id + "'";
            statement.execute(quere);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                connection.close();
                statement.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        select_row2 = jTable2.getSelectedRow();
        String date = list6.get(select_row2).getDat();
        jTextField5.setText(date.substring(8, 10));
        jTextField6.setText(date.substring(5, 7));
        jTextField7.setText(date.substring(0, 4));
        jTextField8.setText(list6.get(select_row2).getMony());
        jComboBox3.setSelectedItem(list6.get(select_row2).getState());
        jComboBox5.setSelectedItem(list6.get(select_row2).getNots());
        jTable2.clearSelection();
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        int x1 = JOptionPane.showConfirmDialog(this, "are you want to delete this data!");
        if (x1 == 0) {
            if (Running.lock5.equals("0")) {
                Security security = new Security();
                try {
                    connection = security.coneect();
                    statement = connection.createStatement();
                    String query = "delete from outstore where id = '" + list6.get(select_row2).getId() + "'";
                    statement.executeUpdate(query);
                    preparedStatement = connection.prepareStatement("SELECT * FROM allstore WHERE dat = '" + list6.get(select_row2).getDat() + "'");
                    ResultSet set = preparedStatement.executeQuery();
                    while (set.next()) {
                        Data_AllStore d1 = new Data_AllStore(set.getString("dat"), set.getString("in_mony"), set.getString("out_mony"));
                        list7.add(d1);
                    }
                    out_mony = Double.parseDouble(list7.get(0).getOut_mony().toString()) - Double.parseDouble(list6.get(select_row2).getMony());
                    if (out_mony < 0) {
                        out_mony = 0;
                    }
                    if (out_mony == 0 && Double.parseDouble(list7.get(0).getIn_mony().toString()) == 0) {
                        String quere = "delete from allstore where dat = '" + list6.get(select_row2).getDat() + "'";
                        statement.execute(quere);
                    } else {
                        String quere = "update allstore set out_mony = '" + out_mony + "' where dat = '" + list6.get(select_row2).getDat() + "'";
                        statement.execute(quere);
                    }
                    new Store().setVisible(true);
                    this.dispose();
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                } finally {
                    try {
                        connection.close();
                        statement.close();
                    } catch (Exception e) {
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please, Open the lock bafore delete!");
            }
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (select_row2 + 1 < list6.size()) {
            select_row2++;
            String date = list6.get(select_row2).getDat();
            jTextField5.setText(date.substring(8, 10));
            jTextField6.setText(date.substring(5, 7));
            jTextField7.setText(date.substring(0, 4));
            jTextField8.setText(list6.get(select_row2).getMony());
            jComboBox3.setSelectedItem(list6.get(select_row2).getState());
            jComboBox5.setSelectedItem(list6.get(select_row2).getNots());
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (select_row2 - 1 >= 0) {
            select_row2--;
            String date = list6.get(select_row2).getDat();
            jTextField5.setText(date.substring(8, 10));
            jTextField6.setText(date.substring(5, 7));
            jTextField7.setText(date.substring(0, 4));
            jTextField8.setText(list6.get(select_row2).getMony());
            jComboBox3.setSelectedItem(list6.get(select_row2).getState());
            jComboBox5.setSelectedItem(list6.get(select_row2).getNots());
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Show_Store().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    public void Get_data_suppliers() {
        Security security = new Security();
        try {
            connection = security.coneect();
            preparedStatement = connection.prepareStatement("SELECT * FROM suppliers WHERE Y_id = '" + Running.Y_id + "' order by S_name");
            ResultSet set = preparedStatement.executeQuery();
            while (set.next()) {
                Data_Suppliers_Customers d1 = new Data_Suppliers_Customers(set.getString("S_id"), set.getString("S_name"), set.getString("S_address"), set.getString("den"), set.getString("state_den"));
                list1.add(d1);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                connection.close();
                preparedStatement.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }

    public void Get_data_customers() {
        Security security = new Security();
        try {
            connection = security.coneect();
            preparedStatement = connection.prepareStatement("SELECT * FROM customers WHERE Y_id = '" + Running.Y_id + "' order by C_name");
            ResultSet set = preparedStatement.executeQuery();
            while (set.next()) {
                Data_Suppliers_Customers d1 = new Data_Suppliers_Customers(set.getString("C_id"), set.getString("C_name"), set.getString("C_address"), set.getString("C_den"), set.getString("C_state_den"), 0);
                list2.add(d1);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                connection.close();
                preparedStatement.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }

    public void Get_data_jops() {
        Security security = new Security();
        try {
            connection = security.coneect();
            preparedStatement = connection.prepareStatement("SELECT * FROM Jops WHERE Y_id = '" + Running.Y_id + "' order by J_name");
            ResultSet set = preparedStatement.executeQuery();
            while (set.next()) {
                Data_Jops d1 = new Data_Jops(set.getString("J_id"), set.getString("J_name"), set.getString("J_jop"), set.getString("J_address"), set.getString("J_vodavon"), set.getString("J_etsalat"), set.getString("J_we"), set.getString("J_nots"));
                list3.add(d1);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                connection.close();
                preparedStatement.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }

    public void Get_date_state() {
        Security security = new Security();
        try {
            connection = security.coneect();
            preparedStatement = connection.prepareStatement("SELECT * FROM statestore");
            ResultSet set = preparedStatement.executeQuery();
            while (set.next()) {
                Data_StateStore d1 = new Data_StateStore(set.getString("id"), set.getString("state"));
                list4.add(d1);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                connection.close();
                preparedStatement.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }

    public void show_data1() {
        Security security = new Security();
        try {
            connection = security.coneect();
            preparedStatement = connection.prepareStatement("select * from instore WHERE Y_id = '" + Running.Y_id + "'");
            ResultSet set = preparedStatement.executeQuery();
            DefaultTableModel mm = (DefaultTableModel) jTable1.getModel();
            Object[] col = new Object[5];
            while (set.next()) {
                Date_InStore d1 = new Date_InStore(set.getString("id"), set.getString("dat"), set.getString("mony"), set.getString("state"), set.getString("nots"));
                list5.add(d1);
            }
            for (int i = 0; i < list5.size(); i++) {
                col[4] = i+1;
                col[3] = list5.get(i).getDat();
                col[2] = list5.get(i).getMony();
                col[1] = list5.get(i).getState();
                col[0] = list5.get(i).getNots();
                mm.addRow(col);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                connection.close();
                preparedStatement.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }

    public void Show_date2() {
        Security security = new Security();
        try {
            connection = security.coneect();
            preparedStatement = connection.prepareStatement("select * from outstore WHERE Y_id = '" + Running.Y_id + "'");
            ResultSet set = preparedStatement.executeQuery();
            DefaultTableModel mm = (DefaultTableModel) jTable2.getModel();
            Object[] col = new Object[5];
            while (set.next()) {
                Date_InStore d1 = new Date_InStore(set.getString("id"), set.getString("dat"), set.getString("mony"), set.getString("state"), set.getString("nots"));
                list6.add(d1);
            }
            for (int i = 0; i < list6.size(); i++) {
                col[4] = i+1;
                col[3] = list6.get(i).getDat();
                col[2] = list6.get(i).getMony();
                col[1] = list6.get(i).getState();
                col[0] = list6.get(i).getNots();
                mm.addRow(col);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                connection.close();
                preparedStatement.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Store().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
